# Generated by Django 4.2.7 on 2024-05-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAPP', '0002_alter_lugares_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=10)),
                ('nombre_propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa_propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit_propietario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excursiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacion', models.CharField(max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_retorno', models.DateTimeField()),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPP.lugares')),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAPP.transporte')),
            ],
        ),
    ]
