# Generated by Django 4.2.7 on 2024-05-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAPP', '0007_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursiones',
            name='fecha_retorno',
        ),
        migrations.RemoveField(
            model_name='excursiones',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='excursiones',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='lugares',
            name='precio',
        ),
        migrations.AddField(
            model_name='excursiones',
            name='precio',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugares',
            name='ubicacionGEO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_retorno', models.DateTimeField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAPP.excursiones')),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAPP.transporte')),
            ],
        ),
    ]
