# Generated by Django 4.2.7 on 2024-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAPP', '0008_remove_excursiones_fecha_retorno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='DNI_pasaporte',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
